# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLShortener',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date_started')),
                ('end_date', models.DateTimeField(verbose_name='date_ended')),
                ('uuid', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('visits', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('users_visible_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
