# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-13 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortenurls', '0002_auto_20180713_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortener',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='users_visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
